---
- name: "Check if Helm is installed"
  ansible.builtin.shell: command -v helm >/dev/null 2>&1
  register: helm_exists
  changed_when: false
  failed_when: false

- name: "Install Helm"
  when: helm_exists.rc > 0
  block:
    - name: "Get Helm installer"
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: "/tmp/get_helm.sh"
        mode: 0755

    - name: "Run the installer"
      become: true
      ansible.builtin.shell: "/tmp/get_helm.sh"

- name: Add helm completion and aliases to zsh
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (helm completion)"
    block: |
      source <(helm completion zsh)
