---
- name: Install Letsencrypt Cluster Issuer Production
  kubernetes.core.k8s:
    state: "{{ 'present' if letsencrypt_issuer_enabled else 'absent' }}"
    definition: "{{ lookup('template', 'clusterissuer_production.yml.j2') | from_yaml }}"

- name: Install Letsencrypt Cluster Issuer Stagging
  kubernetes.core.k8s:
    state: "{{ 'present' if letsencrypt_issuer_enabled else 'absent' }}"
    definition: "{{ lookup('template', 'clusterissuer_stagging.yml.j2') | from_yaml }}"
