---
truenas_csi_iscsi_enabled: false

truenas_csi_iscsi_helm_repo_name: "democratic-csi"
truenas_csi_iscsi_helm_repo_url: "https://democratic-csi.github.io/charts/"

truenas_csi_iscsi_helm_version: 0.15.0

truenas_csi_iscsi_namespace: truenas-csi

truenas_csi_iscsi_instance_name: truenas-csi-iscsi

truenas_csi_iscsi_values: {}
