---
cert_manager_helm_repo_name: "jetstack"
cert_manager_helm_repo_url: "https://charts.jetstack.io"

cert_manager_namespace: cert-manager

cert_manager_cert_manager_enabled: false

cert_manager_cert_manager_helm_version: v1.17.2

cert_manager_cert_manager_instance_name: cert-manager

cert_manager_trust_manager_enabled: false

cert_manager_trust_manager_helm_version: v0.17.1

cert_manager_trust_manager_instance_name: trust-manager
